// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkskJFpmUNbop-0HB4ixoN5ENu98Utei4',
    appId: '1:991177390318:web:033cd5b9619edfc7441bff',
    messagingSenderId: '991177390318',
    projectId: 'weddings-app-1a13a',
    authDomain: 'weddings-app-1a13a.firebaseapp.com',
    storageBucket: 'weddings-app-1a13a.firebasestorage.app',
    measurementId: 'G-YZ5108NPN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByWmWp1SHk6Zn3U4BCUs1Cfz3o3dPpqw8',
    appId: '1:991177390318:android:bf4c94688cd03388441bff',
    messagingSenderId: '991177390318',
    projectId: 'weddings-app-1a13a',
    storageBucket: 'weddings-app-1a13a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-2zvg5hT-nR3NTBB3rmRJ2FwcVnwWQOE',
    appId: '1:991177390318:ios:dd113322f0cd983a441bff',
    messagingSenderId: '991177390318',
    projectId: 'weddings-app-1a13a',
    storageBucket: 'weddings-app-1a13a.firebasestorage.app',
    androidClientId: '991177390318-g0jerfrqd923t9oar7qht0jon8883buq.apps.googleusercontent.com',
    iosClientId: '991177390318-u7hrsl7kncemibgh8sahi4b24ei23vat.apps.googleusercontent.com',
    iosBundleId: 'com.example.weddingGameFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-2zvg5hT-nR3NTBB3rmRJ2FwcVnwWQOE',
    appId: '1:991177390318:ios:dd113322f0cd983a441bff',
    messagingSenderId: '991177390318',
    projectId: 'weddings-app-1a13a',
    storageBucket: 'weddings-app-1a13a.firebasestorage.app',
    androidClientId: '991177390318-g0jerfrqd923t9oar7qht0jon8883buq.apps.googleusercontent.com',
    iosClientId: '991177390318-u7hrsl7kncemibgh8sahi4b24ei23vat.apps.googleusercontent.com',
    iosBundleId: 'com.example.weddingGameFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkskJFpmUNbop-0HB4ixoN5ENu98Utei4',
    appId: '1:991177390318:web:3cad644288891830441bff',
    messagingSenderId: '991177390318',
    projectId: 'weddings-app-1a13a',
    authDomain: 'weddings-app-1a13a.firebaseapp.com',
    storageBucket: 'weddings-app-1a13a.firebasestorage.app',
    measurementId: 'G-QJWXLBVYLK',
  );
}
